[project]
name = "thesis"
version = "0.1.0"
description = "2048 Game AI with PPO"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "matplotlib>=3.10.0",
    "numpy>=2.2.3",
    "torch>=2.6.0",
]

[tool.pip]
extra-index-url = ["https://download.pytorch.org/whl/cu118"] 
